# Generated by Django 5.2.1 on 2025-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=50, verbose_name='Nombres')),
                ('pais', models.CharField(default='', max_length=50, verbose_name='Pais')),
                ('pasaporte', models.CharField(default='', max_length=50, verbose_name='Pasaporte')),
                ('edad', models.PositiveIntegerField(default=18)),
                ('apodo', models.CharField(default='', max_length=50, verbose_name='Apodo')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__gte', 18)), name='edad_mayor_o_igual_18_prueba_cliente')],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=50, verbose_name='Nombres')),
                ('pais', models.CharField(default='', max_length=50, verbose_name='Pais')),
                ('pasaporte', models.CharField(default='', max_length=50, verbose_name='Pasaporte')),
                ('edad', models.PositiveIntegerField(default=18)),
                ('apodo', models.CharField(default='', max_length=50, verbose_name='Apodo')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__gte', 18)), name='edad_mayor_o_igual_18_prueba_empleado')],
            },
        ),
    ]
