# Generated by Django 5.2.1 on 2025-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombres')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('pasaporte', models.CharField(max_length=50, verbose_name='Pasaporte')),
                ('edad', models.PositiveIntegerField()),
                ('apodo', models.CharField(max_length=50, verbose_name='Apodo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
    ]
