# Generated by Django 5.2.1 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('pais', 'apodo')},
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(condition=models.Q(('edad__gte', 18)), name='edad_mayor_o_igual_18'),
        ),
    ]
