# Generated by Django 5.2.1 on 2025-05-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='autor')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
    ]
