# Generated by Django 5.2.1 on 2025-05-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lector', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
        ),
    ]
