# Generated by Django 5.2.1 on 2025-05-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
