# Generated by Django 5.2.1 on 2025-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_rename_apellidos_lector_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='nacionalidad'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='autor'),
        ),
    ]
