# Generated by Django 5.2.1 on 2025-05-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libros', 'verbose_name_plural': 'Libros'},
        ),
    ]
